### ISSUE TITLE
Error: watch EMFILE

### ISSUE THREAD

**Issue by donpinkus** [StephenGrider/ReactStarter#1]
After cloning the repo and running `npm install`, when I run `gulp` I get this error:

```
fs.js:1056
    throw errnoException(process._errno, 'watch');
          ^
Error: watch EMFILE
    at errnoException (fs.js:1024:11)
    at FSWatcher.start (fs.js:1056:11)
    at Object.fs.watch (fs.js:1081:11)
    at watch (/Users/donaldpinkus/Desktop/learn-react/ReactStarter/node_modules/gulp-server-livereload/node_modules/node-watch/lib/watch.js:221:8)
    at /Users/donaldpinkus/Desktop/learn-react/ReactStarter/node_modules/gulp-server-livereload/node_modules/node-watch/lib/watch.js:230:9
    at /Users/donaldpinkus/Desktop/learn-react/ReactStarter/node_modules/gulp-server-livereload/node_modules/node-watch/lib/watch.js:41:14
    at Array.forEach (native)
    at /Users/donaldpinkus/Desktop/learn-react/ReactStarter/node_modules/gulp-server-livereload/node_modules/node-watch/lib/watch.js:38:18
    at ReaddirReq.Req.done (/Users/donaldpinkus/Desktop/learn-react/ReactStarter/node_modules/gulp-watch/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:143:5)
    at ReaddirReq.done (/Users/donaldpinkus/Desktop/learn-react/ReactStarter/node_modules/gulp-watch/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:90:22)
```

It sounds like `Error: watch EMFILE` usually pops up when it's asked to watch a file that doesn't exist. Is anyone else getting this from a fresh clone of ReactStarter?

Full terminal output for git cloning, npm install, and gulp:

```
Donalds-MacBook-Pro:learn-react · git clone git@github.com:StephenGrider/ReactStarter.git
Cloning into 'ReactStarter'...
remote: Counting objects: 43, done.
remote: Total 43 (delta 0), reused 0 (delta 0), pack-reused 43
Receiving objects: 100% (43/43), 6.68 KiB | 0 bytes/s, done.
Resolving deltas: 100% (14/14), done.
Checking connectivity... done.
```

```
Donalds-MacBook-Pro:learn-react · cd ReactStarter/
```

```
Donalds-MacBook-Pro:ReactStarter (master) · sudo npm install
npm WARN package.json react-starter@1.0.0 No repository field.

> fsevents@0.3.6 install /Users/donaldpinkus/Desktop/learn-react/ReactStarter/node_modules/watchify/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/fse.node: Finished

> fsevents@0.3.6 install /Users/donaldpinkus/Desktop/learn-react/ReactStarter/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/fse.node: Finished

> ws@0.4.31 install /Users/donaldpinkus/Desktop/learn-react/ReactStarter/node_modules/gulp-server-livereload/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished

> ws@0.4.31 install /Users/donaldpinkus/Desktop/learn-react/ReactStarter/node_modules/gulp-server-livereload/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
-
> node-sass@3.2.0 install /Users/donaldpinkus/Desktop/learn-react/ReactStarter/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/donaldpinkus/Desktop/learn-react/ReactStarter/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-11/binding.node

> node-sass@3.2.0 postinstall /Users/donaldpinkus/Desktop/learn-react/ReactStarter/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

` /Users/donaldpinkus/Desktop/learn-react/ReactStarter/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-11/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.
node-notifier@4.2.3 node_modules/node-notifier
├── shellwords@0.1.0
├── growly@1.2.0
├── which@1.1.1 (is-absolute@0.1.7)
├── minimist@1.1.1
├── lodash.clonedeep@3.0.1 (lodash._bindcallback@3.0.1, lodash._baseclone@3.3.0)
├── semver@4.3.6
└── cli-usage@0.1.1 (minimist@0.2.0, marked@0.3.3, marked-terminal@0.1.0)

gulp-util@3.0.6 node_modules/gulp-util
├── array-differ@1.0.0
├── array-uniq@1.0.2
├── beeper@1.1.0
├── lodash._reevaluate@3.0.0
├── lodash._reinterpolate@3.0.0
├── lodash._reescape@3.0.0
├── object-assign@3.0.0
├── replace-ext@0.0.1
├── vinyl@0.5.0 (clone@1.0.2, clone-stats@0.0.1)
├── multipipe@0.1.2 (duplexer2@0.0.2)
├── lodash.template@3.6.2 (lodash._basetostring@3.0.1, lodash._basecopy@3.0.1, lodash._basevalues@3.0.0, lodash.templatesettings@3.1.0, lodash.restparam@3.6.1, lodash.escape@3.0.0, lodash._isiterateecall@3.0.9, lodash.keys@3.1.2)
├── chalk@1.1.0 (supports-color@2.0.0, escape-string-regexp@1.0.3, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── dateformat@1.0.11 (get-stdin@4.0.1, meow@3.3.0)
├── minimist@1.1.1
└── through2@2.0.0 (readable-stream@2.0.1, xtend@4.0.0)

gulp-concat@2.6.0 node_modules/gulp-concat
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
└── concat-with-sourcemaps@1.0.2 (source-map@0.4.2)

gulp-watch@4.2.4 node_modules/gulp-watch
├── path-is-absolute@1.0.0
├── is-glob@1.1.3
├── glob-parent@1.2.0
├── vinyl-file@1.1.1 (strip-bom@1.0.0, graceful-fs@3.0.8)
├── vinyl@0.4.6 (clone-stats@0.0.1, clone@0.2.0)
├── anymatch@1.1.0 (minimatch@1.0.0)
├── readable-stream@1.1.13 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
└── chokidar@1.0.3 (arrify@1.0.0, async-each@0.1.6, is-binary-path@1.0.1, readdirp@1.3.0, fsevents@0.3.6)

vinyl-source-stream@1.1.0 node_modules/vinyl-source-stream
├── vinyl@0.4.6 (clone-stats@0.0.1, clone@0.2.0)
└── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)

gulp@3.9.0 node_modules/gulp
├── pretty-hrtime@1.0.0
├── interpret@0.6.2
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.1.1
├── tildify@1.1.0 (os-homedir@1.0.0)
├── v8flags@2.0.9 (user-home@1.1.1)
├── chalk@1.1.0 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── semver@4.3.6
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── liftoff@2.1.0 (extend@2.0.1, rechoir@0.6.1, flagged-respawn@0.3.1, findup-sync@0.2.1, resolve@1.1.6)
└── vinyl-fs@0.3.13 (graceful-fs@3.0.8, strip-bom@1.0.0, defaults@1.0.2, vinyl@0.4.6, mkdirp@0.5.1, glob-stream@3.1.18, through2@0.6.5, glob-watcher@0.0.6)

watchify@2.6.2 node_modules/watchify
├── xtend@4.0.0
├── chokidar@0.12.6 (async-each@0.1.6, fsevents@0.3.6, readdirp@1.3.0)
└── through2@0.5.1 (xtend@3.0.0, readable-stream@1.0.33)

browserify@9.0.8 node_modules/browserify
├── https-browserify@0.0.0
├── tty-browserify@0.0.0
├── builtins@0.0.7
├── constants-browserify@0.0.1
├── process@0.10.1
├── path-browserify@0.0.0
├── os-browserify@0.1.2
├── isarray@0.0.1
├── inherits@2.0.1
├── commondir@0.0.1
├── string_decoder@0.10.31
├── stream-browserify@1.0.0
├── defined@0.0.0
├── has@1.0.0
├── shell-quote@0.0.1
├── domain-browser@1.1.4
├── shallow-copy@0.0.1
├── duplexer2@0.0.2
├── deep-equal@1.0.0
├── querystring-es3@0.2.1
├── assert@1.3.0
├── punycode@1.2.4
├── util@0.10.3
├── parents@1.0.1 (path-platform@0.11.15)
├── concat-stream@1.4.10 (typedarray@0.0.6)
├── vm-browserify@0.0.4 (indexof@0.0.1)
├── events@1.0.2
├── timers-browserify@1.4.1 (process@0.11.1)
├── read-only-stream@1.1.1 (readable-wrap@1.0.0)
├── console-browserify@1.1.0 (date-now@0.1.4)
├── through2@1.1.1 (xtend@4.0.0)
├── xtend@3.0.0
├── http-browserify@1.7.0 (Base64@0.2.1)
├── shasum@1.0.1 (sha.js@2.3.6, json-stable-stringify@0.0.1)
├── url@0.10.3 (punycode@1.3.2, querystring@0.2.0)
├── subarg@1.0.0 (minimist@1.1.1)
├── labeled-stream-splicer@1.0.2 (stream-splicer@1.3.2)
├── buffer@3.3.0 (ieee754@1.1.6, is-array@1.0.1, base64-js@0.0.8)
├── resolve@1.1.6
├── browser-resolve@1.9.0
├── glob@4.5.3 (inflight@1.0.4, once@1.3.2, minimatch@2.0.8)
├── JSONStream@0.10.0 (through@2.3.7, jsonparse@0.0.5)
├── deps-sort@1.3.9 (JSONStream@1.0.4)
├── readable-stream@1.1.13 (core-util-is@1.0.1)
├── syntax-error@1.1.4 (acorn@1.2.2)
├── crypto-browserify@3.9.14 (randombytes@2.0.1, create-hmac@1.1.3, pbkdf2@3.0.4, create-hash@1.1.1, diffie-hellman@3.0.2, create-ecdh@2.0.1, browserify-aes@1.0.1, public-encrypt@2.0.1, browserify-sign@3.0.2)
├── browserify-zlib@0.1.4 (pako@0.2.7)
├── insert-module-globals@6.5.1 (process@0.11.1, xtend@4.0.0, combine-source-map@0.3.0, lexical-scope@1.1.1, JSONStream@1.0.4)
├── module-deps@3.8.1 (defined@1.0.0, xtend@4.0.0, stream-combiner2@1.0.2, JSONStream@1.0.4, detective@4.1.1)
└── browser-pack@4.0.4 (umd@3.0.1, defined@1.0.0, through2@0.5.1, combine-source-map@0.3.0, JSONStream@1.0.4)

gulp-server-livereload@1.4.0 node_modules/gulp-server-livereload
├── connect-inject@0.3.2
├── node-watch@0.3.4
├── open@0.0.5
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── multiline@1.0.2 (strip-indent@1.0.1)
├── node.extend@1.0.10 (is@0.3.0)
├── connect@3.1.1 (utils-merge@1.0.0, parseurl@1.3.0, finalhandler@0.1.0, debug@1.0.4)
├── serve-static@1.5.4 (utils-merge@1.0.0, escape-html@1.0.1, parseurl@1.3.0, send@0.8.5)
├── gulp-util@2.2.20 (lodash._reinterpolate@2.4.1, chalk@0.5.1, minimist@0.2.0, vinyl@0.2.3, lodash.template@2.4.1, multipipe@0.1.2, dateformat@1.0.11)
├── serve-index@1.1.6 (parseurl@1.3.0, batch@0.5.1, accepts@1.0.7)
├── vinyl-fs@1.0.0 (merge-stream@0.1.8, object-assign@2.1.1, graceful-fs@3.0.8, strip-bom@1.0.0, vinyl@0.4.6, mkdirp@0.5.1, through2@0.6.5, duplexify@3.4.2, glob-stream@4.1.1, glob-watcher@0.0.8)
├── through2@0.5.1 (xtend@3.0.0, readable-stream@1.0.33)
└── socket.io@1.0.6 (debug@0.7.4, has-binary-data@0.1.1, socket.io-parser@2.2.0, socket.io-adapter@0.2.0, engine.io@1.3.1, socket.io-client@1.0.6)

react@0.13.3 node_modules/react
└── envify@3.4.0 (through@2.3.7, jstransform@10.1.0)

reactify@1.1.1 node_modules/reactify
├── through@2.3.7
└── react-tools@0.13.3 (jstransform@10.1.0, commoner@0.10.3)

gulp-react@3.0.1 node_modules/gulp-react
├── object-assign@2.1.1
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
└── react-tools@0.13.3 (jstransform@10.1.0, commoner@0.10.3)

gulp-sass@2.0.3 node_modules/gulp-sass
├── object-assign@2.1.1
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
└── node-sass@3.2.0 (get-stdin@4.0.1, async-foreach@0.1.3, chalk@1.1.0, nan@1.8.4, meow@3.3.0, mkdirp@0.5.1, glob@5.0.12, npmconf@2.1.2, gaze@0.5.1, request@2.58.0, sass-graph@2.0.0, pangyp@2.2.1)
```

```
Donalds-MacBook-Pro:ReactStarter (master) · gulp
[14:28:58] Using gulpfile ~/Desktop/learn-react/ReactStarter/gulpfile.js
[14:28:58] Starting 'build'...
[14:28:58] Finished 'build' after 3.11 ms
[14:28:58] Starting 'serve'...
[14:28:58] Starting 'sass'...
[14:28:58] Finished 'sass' after 5.92 ms
[14:28:58] Starting 'watch'...
[14:28:58] Finished 'watch' after 6.99 ms
[14:28:58] Webserver started at http://localhost:8000

fs.js:1056
    throw errnoException(process._errno, 'watch');
          ^
Error: watch EMFILE
    at errnoException (fs.js:1024:11)
    at FSWatcher.start (fs.js:1056:11)
    at Object.fs.watch (fs.js:1081:11)
    at watch (/Users/donaldpinkus/Desktop/learn-react/ReactStarter/node_modules/gulp-server-livereload/node_modules/node-watch/lib/watch.js:221:8)
    at /Users/donaldpinkus/Desktop/learn-react/ReactStarter/node_modules/gulp-server-livereload/node_modules/node-watch/lib/watch.js:230:9
    at /Users/donaldpinkus/Desktop/learn-react/ReactStarter/node_modules/gulp-server-livereload/node_modules/node-watch/lib/watch.js:41:14
    at Array.forEach (native)
    at /Users/donaldpinkus/Desktop/learn-react/ReactStarter/node_modules/gulp-server-livereload/node_modules/node-watch/lib/watch.js:38:18
    at ReaddirReq.Req.done (/Users/donaldpinkus/Desktop/learn-react/ReactStarter/node_modules/gulp-watch/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:143:5)
    at ReaddirReq.done (/Users/donaldpinkus/Desktop/learn-react/ReactStarter/node_modules/gulp-watch/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:90:22)
Donalds-MacBook-Pro:ReactStarter (master) ·
```

**Comment by donpinkus** [comment]
Updating Node resolved the error

**Comment by OKNoah** [comment]
What version of node?

**Comment by donpinkus** [comment]
@OKNoah updating to 0.12.7 resolved the error, unfortunately don't remember what version I was on before :P
