### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by jimlim** [StephenGrider/ReactStarter#12]
Im one of the students in your tutorial. In Section 6 and above, i cloned the ReactStarter and followed your instructions, but it keeps on throwing an error. Can someone tell me whats wrong?

[23:10:05] Using gulpfile C:\react\ReactFlux\ReactStarter\gulpfile.js
[23:10:06] Starting 'build'...
[23:10:06] Finished 'build' after 10 ms
[23:10:06] Starting 'serve'...
[23:10:06] Starting 'sass'...
[23:10:06] Finished 'sass' after 11 ms
[23:10:06] Starting 'watch'...
[23:10:06] Finished 'watch' after 20 ms
[23:10:06] Webserver started at http://localhost:8000
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 127.0.0.1:8000
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1221:19)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at GetAddrInfoReqWrap.asyncCallback [as callback](dns.js:64:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:83:10)

**Comment by DavidGoussev** [comment]
Try changing your port number, you could have a preexisting assignment
already using that port.
