### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by louis-pvs** [StephenGrider/ReactStarter#4]
Hi, 

When I run gulp after npm install, it throw me the error below

[13:56:40] Using gulpfile ~/practice/ReactStarter/gulpfile.js
[13:56:40] Starting 'build'...
[13:56:40] Finished 'build' after 10 ms
[13:56:40] Starting 'serve'...
[13:56:40] Starting 'sass'...
[13:56:40] Finished 'sass' after 26 ms
[13:56:40] Starting 'watch'...
[13:56:40] Finished 'watch' after 18 ms
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: getaddrinfo ENOTFOUND localhost
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:94:26)

**Comment by bloolizard** [comment]
getting same error:

throw errnoException(process._errno, 'watch');

**Comment by lei-clearsky** [comment]
same error: 
fs.js:1062
throw errnoException(process._errno, 'watch');

**Comment by leoman** [comment]
I also get the same error:

[09:54:39] Starting 'serve'...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: getaddrinfo ENOTFOUND localhost
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:94:26)

**Comment by sjafri5** [comment]
Did anyone solve this issue?

**Comment by jaime-franco** [comment]
Hi Guys, i have some issues when running gulp, for solve my problem i noticed that the in the package.js the gulp-server-livereload  was outdate, so i run  "npm i gulp-server-livereload" and that solved my problem.

I hope this help you guys!

**Comment by motleytech** [comment]
@jaime-franco 
I have a very similar issue(not exactly same), but reinstalling `gulp-server-livereload` did not fix my problem. I created another issue regarding that - #6

**Comment by codervince** [comment]
Webserver started at http://localhost:8000
fs.js:1172
    throw errnoException(err, 'watch');
          ^
Error: watch ENFILE
    at exports._errnoException (util.js:746:11)
