### ISSUE TITLE
Gulp with livereload enabled errors out

### ISSUE THREAD

**Issue by motleytech** [StephenGrider/ReactStarter#6]
After cloning ReactStarter and `npm install`.... I ran `gulp` which immediately errors out after the build (I believe `livereload` is the culprit, as disabling livereload in `gulpfile.js` prevents gulp from dying... but, obviously, livereload no longer works)

```
host:ReactStarter username$ gulp
[11:28:14] Using gulpfile ~/programs/react/ReactStarter/gulpfile.js
[11:28:14] Starting 'build'...
[11:28:14] Finished 'build' after 3.72 ms
[11:28:14] Starting 'serve'...
[11:28:14] Starting 'sass'...
[11:28:14] Finished 'sass' after 3.98 ms
[11:28:14] Starting 'watch'...
[11:28:14] Finished 'watch' after 6.29 ms
[11:28:14] Webserver started at http://localhost:8000
2015-11-22 11:28 gulp[49791] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)

... snip ...

2015-11-22 11:28 gulp[49791] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
fs.js:1062
    throw errnoException(process._errno, 'watch');
          ^
2015-11-22 11:28 gulp[49791] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-11-22 11:28 gulp[49791] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
Error: watch EMFILE
    at errnoException (fs.js:1030:11)
    at FSWatcher.start (fs.js:1062:11)
    at Object.fs.watch (fs.js:1087:11)
    at watch (/Users/username/programs/react/ReactStarter/node_modules/gulp-server-livereload/node_modules/node-watch/lib/watch.js:221:8)
    at /Users/username/programs/react/ReactStarter/node_modules/gulp-server-livereload/node_modules/node-watch/lib/watch.js:230:9
    at /Users/username/programs/react/ReactStarter/node_modules/gulp-server-livereload/node_modules/node-watch/lib/watch.js:41:14
    at Array.forEach (native)
    at /Users/username/programs/react/ReactStarter/node_modules/gulp-server-livereload/node_modules/node-watch/lib/watch.js:38:18
    at ReaddirReq.Req.done (/Users/username/programs/react/ReactStarter/node_modules/watchify/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:143:5)
    at ReaddirReq.done (/Users/username/programs/react/ReactStarter/node_modules/watchify/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:90:22)
2015-11-22 11:28 gulp[49791] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
```

Running `npm install gulp-server-livereload` **does not** fix the issue. The other similar unresolved issue on this repo suggests that reinstalling (or upgrading) livereload solved their problem. However, that didn't work in my case. I am still seeing the exact same error.

Any help is appreciated... it would be good to get livereload working.

**Comment by lnegi** [comment]
Remove the livereload part for the moment and just run the server .pipe(server({
      open: true
    })); until we get some response on the issue.

**Comment by sheadawson** [comment]
I'm also getting this error, would be nice to get a proper solution

**Comment by codervince** [comment]
Yes, am continuing with the course sans live-reload but would like to know how to get it to work. In the course discussions, some people obviously have
